name: CI basic pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:

    backend:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./tn_app
        steps:
            - name: Checkout commits
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.10'
                    cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ../requirements.txt
            - name: Run tests
              run: |
                  pytest test_pipeline.py
              

    frontend:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./tn_frontend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install dependencies
              run: npm ci

